### ISSUE TITLE
LabelSmoothing running error

### ISSUE THREAD

**Issue by cuihx13** [harvardnlp/annotated-transformer#38]
When I run the case of class LabelSmoothing, I met a problem showns as follows:

RuntimeError: invalid argument 3: Index is supposed to be a vector at d:\build\pytorch\pytorch-0.4.1\aten\src\th\generic\thtensormath.cpp:569.

I find this line "true_dist.index_fill_(0, mask.squeeze(), 0)" cause the error because mask is blank.

Besides, the second case still has problem. The second case is :
>>>crit = LabelSmoothing(5, 0, 0.4)
>>>predict = torch.FloatTensor([[0, 0.2, 0.7, 0.1, 0],
                             [0, 0.2, 0.7, 0.1, 0], 
                             [0, 0.2, 0.7, 0.1, 0]])
>>>v = crit(Variable(predict.log()), 
         Variable(torch.LongTensor([2, 1, 0])))

# Show the target distributions expected by the system.
>>>plt.imshow(crit.true_dist)
>>>None

The result of v is "inf".

Does anyone have the same problem?
I am wandering whether the label smoothing works efficiently. How about deleting the label smoothing process in the project.

Hope your reply. Thanks a lot!

**Comment by liquor233** [comment]
I encountered the same error, have u fixed it yet?

**Comment by Unilmalas** [comment]
apparently the problem lies in the dimension check of the mask in class LabelSmoothing(nn.Module):
mask.dim() returns 1 for empty tensors; for a quick fix change if mask.dim() > 0: to if mask.dim() > 1:

Edit: while I am at it: to fix the deprecation warning change
self.criterion = nn.KLDivLoss(size_average=False)
to
self.criterion = nn.KLDivLoss(reduction = 'none')

the plot then throws an exception, change
plt.plot(np.arange(1, 100), [loss(x) for x in range(1, 100)])
to
plt.plot(np.arange(1, 100), [torch.mean(loss(x)) for x in range(1, 100)])
to fix that

**Comment by Unilmalas** [comment]
fixed some more deprecated errors etc, working up to copy task, 
[The Annotated Transformer.zip](https://github.com/harvardnlp/annotated-transformer/files/5034788/The.Annotated.Transformer.zip)

also fixed the GPU issues: 
[The Annotated Transformer.zip](https://github.com/harvardnlp/annotated-transformer/files/5056342/The.Annotated.Transformer.zip)

also attention vis fixed:
[The Annotated TransformerV02.zip](https://github.com/harvardnlp/annotated-transformer/files/5080753/The.Annotated.TransformerV02.zip)
