### ISSUE TITLE
label smoothing running error

### ISSUE THREAD

**Issue by cuihx13** [harvardnlp/annotated-transformer#39]
When I run the case of class LabelSmoothing, I met a problem showns as follows:

RuntimeError: invalid argument 3: Index is supposed to be a vector at d:\build\pytorch\pytorch-0.4.1\aten\src\th\generic\thtensormath.cpp:569.

I find this line "true_dist.index_fill_(0, mask.squeeze(), 0)" cause the error because mask is blank.

Besides, the second case still has problem. The second case is :

            crit = LabelSmoothing(5, 0, 0.4)
            predict = torch.FloatTensor([[0, 0.2, 0.7, 0.1, 0],
            [0, 0.2, 0.7, 0.1, 0],
            [0, 0.2, 0.7, 0.1, 0]])
            v = crit(Variable(predict.log()),
            Variable(torch.LongTensor([2, 1, 0])))
            plt.imshow(crit.true_dist)
            None

The result of v is "inf".

Does anyone have the same problem?
I am wandering whether the label smoothing works efficiently. How about deleting the label smoothing process in the project.

Hope your reply. Thanks a lot!

**Comment by catqaq** [comment]
Hi, i got the same problem. The 3rd sample's label is [0.0000, 0.0000, 0.0000, 0.0000, 0.0000] after smoothing, that's why v is 'inf'. Any idea? Thanks a lot!

**Comment by catqaq** [comment]
Things are like this：
crit = LabelSmoothing(5, 0, 0.4) #size=5, padding_idx=0, smoothing=0.4
padding_idx=0 means that category 1 is  considered ’padding'. In fact, there are only 4 categories.
So the 3rd sample with label '0' actually refers to the padding. After label smoothing, its label is all zeros. That's why v is 'inf'.

true_dist[:, self.padding_idx] = 0 
Hope it helpful!
